# Generated by Django 3.2.5 on 2022-07-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='lname',
            field=models.CharField(max_length=128),
        ),
    ]
